version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DATABASE: db-matrixflowr
      POSTGRES_USER: db-matrixflowr
      POSTGRES_PASSWORD: pwd-matrixflowr
    volumes:
      - ./data:/var/lib/postgresql/data