# Generated by Django 4.2.3 on 2023-07-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='flow',
            name='is_opened',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
